#----------------------------------------------------------------------
# This file was generated by ./create.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

IconError = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAlpJ"
    "REFUOI2lkr1PU2EUh5+3t/fe3vbSllYaIaA0MNAADhoxYWAiiCF+gCQaF4mJDpowOfgPGDVx"
    "YzIsmrBCHFwcdDAMxEQ0IAJ+xBJDtQUhUuzXfe99HTQQIx+DZ/yd33nOR44Q/F/49krOnzp3"
    "fbZv4NZeHm23CRZ7ztyOdaTuhqJW9yW71njwaeH5Tj6xE+Bj99mjofbGV7Fa8OVWyawIst82"
    "j3U8fTy97wqfe/tNrSo4FmmqRkbqqaQ6SMR9CI2xqd5+c18Am8W+aKoupQUMrGs3sa4MozUk"
    "qasiVXJk356ATG+/bbU0jltRhSy6W7qjmcQP2ETj9vhk/wV7V4DneCOh403IQgH8xpburq0g"
    "M8scshT53OrIjoDMyYGk3XlkSHN/IBfm8dLvt8FLaUozrwl+mKVq8e3QI2En/wGIYmnM7/+O"
    "8+IZ7vISypXbbYIWmCaOZtBaX4MvqD/8C5DRa84bCV8nG8sozUREoqhCYate5dcRukFZutiG"
    "Rlt1uGvUCg/Anz/IHk5lQze6Eu7MO5TfBMfD+/oFonUIQM5Nox1sRpVdVNklLAUT6eWNi/n1"
    "iJb1xYaDV3sG1UYOpAIF3toqWks74dEJAoOXcd68RC2lQQ+AVOge2MJvJouVss84kbrvS+io"
    "tZ+gAA+oVBBWFcJvgO5HhCKoSgUlQCnIS0nSCtBsWXf8CqELW0eLW+CBciR6oB5vborK6D2E"
    "HYbJJ9gNjaiiAhMEAlEReEL9vkGutU2pmLmpHBfpKjwFTrmEk07j4eIl6lCaiSNdXOmhXI9s"
    "oWSfXs+JX1/m7hX1hFwuAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
IconMissing = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAkBJ"
    "REFUOI2Nk91Lk2EYxn/3u8d3W++c21KT6YGxA8/6guwDgk5iS7RAkMACxf+h8wj6GzrzVAoR"
    "SkuHHhQIRRFlkUkomMZaqdtc+3i39u7pYDoNJbzgOnqu+3qu57nvW4QD6AkP6f4TQfrcCgsg"
    "VyS/tqEns4+NCeD5frHsM/B2DOsn5yL62oUuIejTGDunFUeTTAtzC/BxVc8Wxo2bQHG/gSc8"
    "pFduXSEcadN83xKS6T1nlwta/NDZCi8+wdhLJyHPVASwRYDWO9WZ21clarnha0JjKsEQqOo9"
    "k4pTS3I2Irxa0sx9IG5PGDEDiF3sIupugMV1XReXK7VCQ2o0FXhM4d2y5sxJob1ZokBMdQzr"
    "gXAIFtc0v+3azQCOA+k8FEp7KXxeCPmE1V9wqQt+DlQH1HE/vYmUJtQo3BvUVDVkckIqd7A9"
    "hoDbhAePoFSBlibpVYaBv1yBZFpzqvOQph6Cu6PwZV1DedOvlAHzixCwjlYM8McBs0Eo22XU"
    "m8/bWavR71lPbNF7P7QjONyswVX75OVvGYLBAOVsNavILU2ppu4Rry/E9OvskRJ4rQDVKlBK"
    "TolATEdT0y3NAXLFoz3B54WNzQwSD103gBlS8/HtgmAqcLT8l6aC7YJAaj4OzNRHWZ9/ukJb"
    "XzhoafIlqQ/SLkwFlluTzgskJxPy9kYEsF07BhVJjD3E095t61DEUUEaPRq3os5iWbAzq/Bj"
    "fFbeD14GbPh3G3fRo0+P9qP8fbiOWQA4hTyV7KQsjBxY57+FQelkdQRp4wAAAABJRU5ErkJg"
    "gg==")

#----------------------------------------------------------------------
IconNew = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAnZJ"
    "REFUOI11k0tIlFEUx3/3zuubMb6sHCMTRVvUKrQSIRISURSEUVBxUeCmNoKEO9sGBbZs12Ii"
    "cyGpmKQkTom4SCQzCYwkSsfyNY6lQ+O857a4+cK6cDlw/o97zoW/EBw51Srvdh2O7HqceRkA"
    "RJbCxAIDYunxC2DkIFkcMLCrM01DXLhfebP2HDVXwHRpILQDr6bh2dBX+HzXJ1af1wJx7aCv"
    "jdyWQHmHUi+nlHriU8pzL62oWFRULKrGB2n19I3GyjuUIrclIMAmACuAymkebmz1um+UQ/e4"
    "4tOS4JhTkBrNB8BS5ce/kU/BacUdjyDL9Lp7H0WHxUpPlQSqKO6ubCoTdPbDl1VBKHL0YyIx"
    "jXX2Q1OZgOLuSqBKqsL2htZaC11jiq2wJidTMPnBf8ggHNN1KwxdY4rWWguqsL1BYhZ5HDZ4"
    "PQsZBszMzrP8fQEiS/vq6BrfFvzMzM6TYWiuwwaYRR4r0jCPuyDyO8jkQzdw/q+qYE+fmig9"
    "NI2lJshxlxukYUqcuUQTwObE0cX/dzYntMbIwUpsLeT1KQNpYCnpPcRLvWvUL5b0gs3UzUQI"
    "LC68PgWJnyErkR+D62srtzh5Te+djkIyBCq572QzQRrgyAYn4MhhfW0FdhYHpZhr6yMWAIsB"
    "9ixwFeqKPDCLBFsm2LPBmqm5sQBirq1PAqNsT/tI6tFIx0HaIbG1r09s6V46rjnJEGxP+4DR"
    "3SzY1OW+ZU5ddyPtoNLw6y3Egxq1Z8GJqyCkNtkc3xDvG84CicNhutQzhHmxEnuWFu2iSmmz"
    "eBBCH31ipnkvTOKfcS4dqUMa9Ui7jnM6HiYdHRBT1Ufi/AcWrPoYRXGRIwAAAABJRU5ErkJg"
    "gg==")

#----------------------------------------------------------------------
IconOk = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAA0pJ"
    "REFUOI1Vk11sU2UAhp/v/K3t6WnXrUf2w5RliE4uloAKDuZP4gZGxsARYzBi1MRww4UJwQsv"
    "IDF6wYVcEBM18cKRoDFLYLLJz7KZYJAZkDBiJBOYCmztetZ17WnXtT2nnzeI8Fy/efPcPELw"
    "MHI7W2lix2OB6M5oLGoCZDPZwj/L2RPMclL8wJkH9+K/A7kHgzLDe/o2du/u3MLTjz5FlFoA"
    "sixy+fYfHP/lLANDE6MYbBMDlO8fyL3o+Mwc+2Cf3ftED5nlLMl8El9CVVbRFJWGcAN1gQin"
    "ps7x1pGjDirN4gsqGgB5Rr49+JH9UuszXEj+TKE6j+d7cE9PSkj5U8iFIF1tnXz3oWW/cejT"
    "EaBH5W169vZvP7h7w8uMz5wi76eRUoIQSEACNbpGqugwdiPF1blZ1jevJWipbZdrpi4qIq7u"
    "6l2/kQnnHIqoUqMEUYWGgoJAENQMUgWHizcknzw7wJGuAY5fu0RPxzpEXN2ltNsr+4g6SF+S"
    "LWWQsoL0FaqehiF05gopLk2rHN70DU1Rm4TrMF38FT2Wpt1e2acZQS9So9RwYS6JnlvL6eJZ"
    "mluKmHqIZMahOtfBZ10DrLBiJFyHV0c209EuMY0QWtCLaOFohJmlNLdnohx+8QBwgFfOr0aY"
    "ORqLnRx74XvqTYuE69D743OEm+4SDLTglj2scARtsejmJosTgcmlBQwlQL1mcfr5m4zf+Ykt"
    "Ld3Umxa/z0/yzlg/0aYEq+IxnGKG89kx3IqbU+aX54f+XnRobSuxbrCRtOfSGLR58/HXid/T"
    "fnesH6MhyYpYnGxJQ1NNpheSpIrzQ0ppSR1Mz0nClsWTawJ0Dq8iXXJBh4Tr8NqZzWgNKew6"
    "m8UKlKsCdIUFR1JaUgfV0njllr+BTXUNgTYrFCJkVvj8ypeE/Fo+/m0/nj1LvC6K70mQENBV"
    "lstVrl/Njqb2Fw4JAbQcNfVQRJlZ0xGzDU1FepLrs3d5JBInFNIplytYwQCqKih7Pn9OZpyl"
    "XLX5zr5C5X5MrV8FDV3Thhvbwt1hyyAc0dGECoAnffK5Cnm3TOJWfrTiedv+er/4f0wPsvpr"
    "c2u4VtuhqepOxRAmQLUsC57vn8gveidvvld4KOd/AYCuYU5d+dhHAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
IconWarning = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAm9J"
    "REFUOI2lkEtsTGEYhp//XOacGjNmiFZFNUxLRVq3hSAhERKX2KgNsbGSIAgbiZ0QibDSsKim"
    "EhPCgo2F2IiFxCXu4pKZYqYXPTOjVT1z5sycy2/BgigWvuRbfW++PM8rBP83yt+OH3o37cn0"
    "bjny1w/iD5vrWX9i9P5R+fneIfmma92JP+XERAr93euWTpq3+HFyYQxqFtbLMsWstaxj760n"
    "/1QYvLTRUGNT04k5kxjOlrCG4jQ0+6iann7RtdH4dwflsc31i9oX5IfynL89nzM36rHsJlLt"
    "yQVu1dv8WwU/KxSubJisJZrGEytaANhx4DN9fRkeXE0B8O5ODrccxJbsvm5PSCD84KzR2gHS"
    "Aenw/Okjhgb7wcmDk2fmbIXxgnV2QoLS5Q1zzLnL32uzNCL+UwAa1wwQ+AGFq18B8Koqr+4W"
    "+Ph2ZG7nNT78SlCtpdVpI9Ssm+DmwM3h1zw8rwqaCZqJ50VoXdSAOjl68ReF4nGzU59hrJRK"
    "P0gD9BjoMUrDLl9KASgCFIFXDYjGdea1JVZf2W5uBdAAlOSMc3p7irD4DEQEz/ku1nO4CELB"
    "d2Z+91UD7DGP1rYE2cxYL3BdHTkW2R9Z27lNKIPgC6QMiSghdiHLwfQK7r6Os3NVhogRx3dD"
    "CCSakMRM1Wgz3aqmt3ScVhsjhJb9A0iiGj7ScXj4/BNUygDoWkBFgAQqTsCsRpPU7LqTGoqm"
    "i6iBEouCFCihAqZBsqmZ1xcGAEg2NQNgeiFCDxE1BRRJCIjRU4ldNEzvllOiFVkLCP0Q35fU"
    "6TW+lGyQCkZUYNs6gRfi1wKklBQLlboBy933DbxL/oFnlTdXAAAAAElFTkSuQmCC")

