#----------------------------------------------------------------------
# This file was generated by create.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

DirContainsError = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAkdJ"
    "REFUOI2FkzFLI0EUx3+zs4lFCm2CkdifcKIJNnKErdXqwMY0lp7aB7+BTT6B12g+g0WsLbxr"
    "ZKNgUBIPFCGwmxiULLtuZneuuHMvuRzcH4aZee/Nf97M+z8hGMfe/v7F/Pz8klIKIf54DcPg"
    "8fHx+uvR0afReCHGD9uWZRWUUowSaK0xDIN+v49t243ayUlxgmB3b8+2LKvw8vKC7/v8Da01"
    "qVSKIAhoNpuNk+PjIoAUwJfdXbtUKhX6/T5BECCEQGs9MaIowjRNZmZmcvl8/vPV1dWR2NnZ"
    "+VYqlVZd18X3fdLpNMPhEAApJUIIgiDANE2klIRhiJSSOI5pt9vfzXw+v/Lw8JCk+vb2lqzj"
    "OE4+MI5j4jhGCJHYM5nMCgcHBwP9G/V6XY+iXq9rx3G01lo7jqO3trbG/Nvb2wNjMBhwdnYG"
    "wOHhIZZlAVAul6nVamSzWTY3N8lms0lm1WoVgF6vh/n09ES1WqXT6XB+fk65XJ6oQBiGY/tK"
    "pQJAp9PB9DyPSqXC2toaAJ7nAdBqtQBwXZfT01Nc100I1tfXkVKSyWQQGxsb4fT0dOr19XXi"
    "5v/h+fl5aDqOczk1NbUahiFCiKRE7+qLogilFIZhJPqQUqKUwvO8SyGAQrFoz83NFZRSSYm0"
    "1sk8KiwhBEoper1eo3lzU0ykvLS8bOdyucJwOPwnCYAQgiiK6Ha7jbvb2+Iv28ibPi4u2rOz"
    "s4UoihKSUQKlFN1ut9FutSab6R0fFhYu0un00ijBO3zfv/5xfz/Wzj8B8y1grhUS2VIAAAAA"
    "SUVORK5CYII=")

#----------------------------------------------------------------------
DirContainsMissing = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAmlJ"
    "REFUOI2Nk01LG1EUhp87cyeJZjIhGIJ0FQlkUTd10SJFoVkUrSiFQttk23/RX9Kti+6EUj/o"
    "BxYs7rKy+FHBEkQImsQZZpRkJjNMZrrR1GIpPnBW55yXc+95jxDcYuF1tfoil8stSSnTAJ7n"
    "9UzTXF/9+PED8OlmsbghMFKt1VZLpdLTcrmMruuIq+xgMMC2bXZ3dzk5OdlcX1t7Dng3BVKv"
    "q9XGzMzMvfHxcSzLwnGcobKiKBiGQaFQYH9/n+3t7dNvm5sloK8K4OWrVxuzs7NTyWSS4+Nj"
    "fN8HIIoi4jgmiiK63S5nZ2dMTEyQSqUyRjb78NfR0XsFmC+Xy3OaptFsNocjh2F49UaBEAIp"
    "JYlEgkajQbFYZGxsbA6YV2u12ttSqTTVbrfxPI8gCPB9H9d1OT8/p91uY1kWlmXhui5CCKIo"
    "Ip/Po+t6IA3DWLRtm0wmQ7VaJY5jut0uvV7v1nqEEGiaxsrKCmEYYhjGolQUxQjDENu2KRaL"
    "t5f6D5aXl2k2mwRBYEhFUTg8PGR0dPROzdd/pGka/X4fUalU2plMpnB5ecn09PSw4F+oqgpA"
    "vV4nl8thmmZHuq67kc1m3+i6Tr1ev9ME6XSaKIrwfX9DCJh/Uql8zufzeJ53J4GRkRFM0+T7"
    "1tYzBfjiOM5X13WRUhLH8X9DSonrujiO8xX4MrTyg6mpRqFQuJdOp/F9f2ika6SUJJNJer0e"
    "nU7n9MfOzh8rA2Gr1XqXSCYfxXFcUlWVVCqFlHIYQRBwcXFBq9Xa3N/bewz04e9rvGbh/uTk"
    "CynlkqqqaYDBYNALw3D958HBrXP+DddTJb75hnFjAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
DirContainsMulti = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAjNJ"
    "REFUOI2NkzFLY0EUhb87jrz4xEoiBEMEC0kpWlhYSAL2VhFbbVastPBH+A/cytbK0sJm8wck"
    "NlqKIK8RFYwkvvdm7mwR3yPurrCnuQz3zLlnhnNF4PBXt3tirf3w3qOqFDDGAOC9J4QAgIhg"
    "jEFVK+1W61guLy/D4uIiIYSSFEJgYmKCt7c3jDHEcYyqIiJfxB8eHrDe+36WZTPjE4r68vJC"
    "kiTU63VqtRre+3KAMQYR6Zs0TSWEgLUWay3GmKKJc45Op8Pj4yNJkhTWS7eqKlZVGQ6HvL6+"
    "luppmuK95/7+ns3NTTqdDufn5wDUajXyPMcYg3MOKyIkScLKygoAqopzDuccq6uriAhxHLOz"
    "s8PFxQVZltFoNPDejwRUlTzPCSGwsLDAOAaDAdZaACqVCtvb25ydnZGmKc1ms3BiStKfiOP4"
    "y9kYw+7uLiEEkiQhiqKRwN3d3T8FvsP19TU3NzejTPR6PZ6ensjz/L8uHx0d8fz8TKPRoNvt"
    "Yr33RFFElmXc3t5+IU9PTzM/P4+1lhACBwcHRFFEu91GVcmybCTQbDbLzykwOTlJr9fj6uoK"
    "gK2tLWZnZ9nY2MA5h6qOsuOcY2pqiuXl5b/sFhnZ29ujWq2yvr5ephE+Eyki4bv39vt9Wq0W"
    "1WqVtbU1oigqe59pDfb9/X1mfInGa71eZ2lpibm5udIRjPZERBgMBjMicPhjf/8kiqKP8VUW"
    "Eay1qCree0SkFDbGMBwOKz9PT49/A2t1LqRIvW5RAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
DirContainsNew = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAApNJ"
    "REFUOI1tk09LI1kUxX/1qur5TExQQSY9TkO7cRubdHCXhZLQiyk6gV66nY0fxpUfwWUg09gN"
    "Q6TIRnCRkcqsbNwIZkxnbChMTFfiq1TV7EJC+uwunHMu988xDJbw/rfXr6tSytrq6moaYDwe"
    "/9BaN/7tdv8E/ponG3MG8pdc7vPu7m7ZcRyKxSKpVAqAIAhot9ucn59ze3t78V+//zug5w3s"
    "X7e3H46OjrZqtRrD4ZCrqytarRYA5XKZ/f191tbWaDQanJ2dfe89PGwDoQWQe/Xqy/Hx8dbB"
    "wQGtVov7+3uUUriuC8Dh4SGPj4/kcjmq1SrZbHbr9PT0S//bt4oAKvl8vlwqlajX6/R6PYIg"
    "WFqM1pper0e9XqdUKpHP58tARbzZ2fnoOA6u6zIajQCIogjP8xYMJpMJAKPRCNd1cRyHNzs7"
    "H0Umk/lg2zae56GUotPp0O12GY/HM/HLywt3d3d0Oh2UUnieh23bZDKZD5YQIptOpxmNRpyc"
    "nCwfFbi8vFyoK5UK6XQaIURWKKXQWuP7/k/FP4Pv+2itUUphaa2HzWZTCSEoFAoLxOvrawAK"
    "hQK2bQMQhiGmadJsNgnDcGiNx+NP/X7/j42NDSaTCVEUEUURSZLMjGzbRgiBlBKlFCsrK/T7"
    "fYIg+CS+3tzUtdaYpolt26RSqVm3eViWhZQSy7IwTROtNV9vbuoCaA4Gg4vpdIppmsRxjBCC"
    "MAxn4jAMEUIQxzGmaTKdThkMBhdAc/bKe2/fPmxubm4JIUiShKenJ7TWAEgpWV9fxzAM4jjG"
    "9/3vHc/bBsKFMOX39j5nMpmylBIp5cIIWmu01jw/P1/80+kshWke798Vi1UhRM0wjDRAkiQ/"
    "4jhu/N1uL8X5f9aHH3zbUxAFAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
DirContainsWarning = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAidJ"
    "REFUOI2l0c9KG1EUx/Hvnc6Nxkm6GYjKCP4BhaggZJlF98Vd+wJ2W7RrfQBRancuI9WFgqFq"
    "tiFEqAtFcaMPIIgQ0HEUDZg7Zq5zu2ooramFHjir8+MD5xwh+L+yXph/BGb/mhBtemNjY/74"
    "+NgcHh6alZWV+Xa5dkBuf3/fXF5emouLC1OtVo2A3HPZ51bo2CmV1vv6+jg/P8f3fTzPY3Vt"
    "bR3o+JcbTI6OjmZrtRqVSoVSqcTDwwPZbDYLTL4EpKq7u9uu6zIyMsLZ2Rl7e3tkMhl6e3vZ"
    "LBa3gVRb4NvW1nJ/fz9xHBPHMScnJ9RqNZRSKKXwPI/PS0vL7YDBgYGBKSkl9Xqder3O3d0d"
    "zWaTIAgIgoAoitBaTwGDfwCbxeJ6Op3m6uqKMAwJw5AoioiiCNu2sW0brTVjY2NMz8ys/Q68"
    "d103b4wBQEqJlBLf97m9vUUIgRCCZrNJOp1meHj4DfAO4JUAvq6ufs/lcs79/T0Axhi01qRS"
    "KfL5PENDQ2it0VrTaDTo7u7Gdd23R0dHixbwaWJiIqOUwrKsFuD7PgcHB5TLZX6FAeI4Znx8"
    "/DUwa2/v7HxxXZcgCFrXTCQShGHI6ekpj4+PANi23Zorpejp6WF2bm7BtixLdnZ20tXV1dIT"
    "iQSe51EoFADwPA8Ax3F+fgLLsjDGIAR82CwWC47jqCiKeHp6QmuNlJKbmxsAkskkjUaj9RVj"
    "DNfX18nFhYXpHzokBE4RC13YAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
FileError = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAk1J"
    "REFUOI2dk71rU2EUh5/3fjRtExtTURClS7tIpSS0xapbbcFawToIdRAXR8HNf0HcHPwLXJQu"
    "dXMRiqCNQktCwEGR1NbY9COtzUeTe3Nz3+Nw0zShi/jA+3nO73Dg/b1K0UlxembZHDo/gueB"
    "aouaJv63X5no0vtr7fntKRSnZ1L23JU4XpGOAiKIaSA7B3gfsulY8mPiRIH9qZlU953xuPzJ"
    "oStVUEZTrJsrEDLhsIH35Xe6fzkoohRQmLqZ6rk9HpfCBuK6YBigJRAFE4gEwzKg1sBZyafP"
    "Jj8l1M7kVDIyOzqh8z+gUoPuENTrgdDqAqWQahVl22Da4NZQloH2LaqZvc9q/9GDum0Wbf4D"
    "92fRozA/V5EmmwuL0s7mwqKUtnZFRKS0tSvrY8Md8fzViQr5WzcqR8JcrEtysS4REVkfG24J"
    "SpdOt+5ERPaePBURkezgUMVy1tbofXyfvewzLuy7bIxfPtGqcvyOc/+L5wDUN9aw3HKF0MvX"
    "nLs3B8BBVTMAuJmvAJS3C5zKlihvF1oFKhej+HYI+iKo74MD9UgsbMfaEv6VbMnxrFyhvJqw"
    "ZEK7h3imhVhdGL4PImjDwmg0EK8ePKEyMLTGMG2qWrPteKtKAe8i0dTomXA85Lo0pGmgpn8Q"
    "QBGYSIOlwPGFlUMnPes5iZaV34b7Utej4XjIdahrQUGbCYONjaKmhWS1lr7r14+tfMSb3khq"
    "MhyOR1wXX+S4AwETKGufJcdJz0vj5Gc64lWoZ3lAZMTXutl7gCmwrv3MQ2l0fOe/ZlJdo7mp"
    "ZpMAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
FileWarning = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAm9J"
    "REFUOI2lkEtsTGEYhp//XOacGjNmiFZFNUxLRVq3hSAhERKX2KgNsbGSIAgbiZ0QibDSsKim"
    "EhPCgo2F2IiFxCXu4pKZYqYXPTOjVT1z5sycy2/BgigWvuRbfW++PM8rBP83yt+OH3o37cn0"
    "bjny1w/iD5vrWX9i9P5R+fneIfmma92JP+XERAr93euWTpq3+HFyYQxqFtbLMsWstaxj760n"
    "/1QYvLTRUGNT04k5kxjOlrCG4jQ0+6iann7RtdH4dwflsc31i9oX5IfynL89nzM36rHsJlLt"
    "yQVu1dv8WwU/KxSubJisJZrGEytaANhx4DN9fRkeXE0B8O5ODrccxJbsvm5PSCD84KzR2gHS"
    "Aenw/Okjhgb7wcmDk2fmbIXxgnV2QoLS5Q1zzLnL32uzNCL+UwAa1wwQ+AGFq18B8Koqr+4W"
    "+Ph2ZG7nNT78SlCtpdVpI9Ssm+DmwM3h1zw8rwqaCZqJ50VoXdSAOjl68ReF4nGzU59hrJRK"
    "P0gD9BjoMUrDLl9KASgCFIFXDYjGdea1JVZf2W5uBdAAlOSMc3p7irD4DEQEz/ku1nO4CELB"
    "d2Z+91UD7DGP1rYE2cxYL3BdHTkW2R9Z27lNKIPgC6QMiSghdiHLwfQK7r6Os3NVhogRx3dD"
    "CCSakMRM1Wgz3aqmt3ScVhsjhJb9A0iiGj7ScXj4/BNUygDoWkBFgAQqTsCsRpPU7LqTGoqm"
    "i6iBEouCFCihAqZBsqmZ1xcGAEg2NQNgeiFCDxE1BRRJCIjRU4ldNEzvllOiFVkLCP0Q35fU"
    "6TW+lGyQCkZUYNs6gRfi1wKklBQLlboBy933DbxL/oFnlTdXAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
Missing = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAkFJ"
    "REFUOI2Nk01PU1EQhp9pb7+4/cQioSxQiOxQEyImGncaKoGYNBI1sNGVv0H3LvwDunYpQUIg"
    "WMSEBQlGozGKGjB2IV+1ipSW3vZyue1xAbQQiGGSWZ05z3nfmTMiHIqepgEjcTJCn0dDByiU"
    "MJbW1NjmsP8FMLG/WPYBfM2Dxuj5VnXtQrsQ1hWO3VO7rMhsCNNz8OWnmiqO+G8Apf0Ab9OA"
    "kbp5mdjpRsXKupDZqJGdDogGoaUBZr7C85nKqiQDbYApAjTcKSRvX5HuOg/8SCvcmiACStUg"
    "dnlHyblW4e2CYvozk+aoP+4A4l1n6Ha7YH5ZVYu37ZpHEXBp4HULH1OKs6eE2AnpBuJa86DR"
    "3xSB+SVFwZSqp0oZskUobdVU6D6I6MLiH7jYDr8ThX6tPkhvOquIBISHtxQVBbmCkDUOj8ch"
    "4HbB42HYsiEalF7N4SBo2ZDJKjpajhjqEfHgGSwsK7D+BjXNAW/mIVR3vMt7PXK7BMu00N5/"
    "y+f1QMC7nF4n8SgCwHb5aJjLudPk1GKOcCSElVd5DeP7uDPUec/nj/Dq3eaxFPj0EJUKYP0a"
    "F4G4urryMhoNYZSOZ0H3wdpaDnndfN0BJMnOTuaLgkuDspL/pkuDfFEgOzsJJKtfWXUOpWjs"
    "iYV1RXFLsOyDr7o1qPMoNgyBzMSqfOhvA0znLsCW9NATPLEuk/q2sjNMwKvwaFSzZAlmbhHS"
    "I1Py6e4lwISD27gXParjaQIt2IfTpwNQLhnY+TGZu39onf8B+hDogI/O4koAAAAASUVORK5C"
    "YII=")

#----------------------------------------------------------------------
New = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAnZJ"
    "REFUOI11k0tIlFEUx3/3zuubMb6sHCMTRVvUKrQSIRISURSEUVBxUeCmNoKEO9sGBbZs12Ii"
    "cyGpmKQkTom4SCQzCYwkSsfyNY6lQ+O857a4+cK6cDlw/o97zoW/EBw51Srvdh2O7HqceRkA"
    "RJbCxAIDYunxC2DkIFkcMLCrM01DXLhfebP2HDVXwHRpILQDr6bh2dBX+HzXJ1af1wJx7aCv"
    "jdyWQHmHUi+nlHriU8pzL62oWFRULKrGB2n19I3GyjuUIrclIMAmACuAymkebmz1um+UQ/e4"
    "4tOS4JhTkBrNB8BS5ce/kU/BacUdjyDL9Lp7H0WHxUpPlQSqKO6ubCoTdPbDl1VBKHL0YyIx"
    "jXX2Q1OZgOLuSqBKqsL2htZaC11jiq2wJidTMPnBf8ggHNN1KwxdY4rWWguqsL1BYhZ5HDZ4"
    "PQsZBszMzrP8fQEiS/vq6BrfFvzMzM6TYWiuwwaYRR4r0jCPuyDyO8jkQzdw/q+qYE+fmig9"
    "NI2lJshxlxukYUqcuUQTwObE0cX/dzYntMbIwUpsLeT1KQNpYCnpPcRLvWvUL5b0gs3UzUQI"
    "LC68PgWJnyErkR+D62srtzh5Te+djkIyBCq572QzQRrgyAYn4MhhfW0FdhYHpZhr6yMWAIsB"
    "9ixwFeqKPDCLBFsm2LPBmqm5sQBirq1PAqNsT/tI6tFIx0HaIbG1r09s6V46rjnJEGxP+4DR"
    "3SzY1OW+ZU5ddyPtoNLw6y3Egxq1Z8GJqyCkNtkc3xDvG84CicNhutQzhHmxEnuWFu2iSmmz"
    "eBBCH31ipnkvTOKfcS4dqUMa9Ui7jnM6HiYdHRBT1Ufi/AcWrPoYRXGRIwAAAABJRU5ErkJg"
    "gg==")

#----------------------------------------------------------------------
Ok = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAA0pJ"
    "REFUOI1Vk11sU2UAhp/v/K3t6WnXrUf2w5RliE4uloAKDuZP4gZGxsARYzBi1MRww4UJwQsv"
    "IDF6wYVcEBM18cKRoDFLYLLJz7KZYJAZkDBiJBOYCmztetZ17WnXtT2nnzeI8Fy/efPcPELw"
    "MHI7W2lix2OB6M5oLGoCZDPZwj/L2RPMclL8wJkH9+K/A7kHgzLDe/o2du/u3MLTjz5FlFoA"
    "sixy+fYfHP/lLANDE6MYbBMDlO8fyL3o+Mwc+2Cf3ftED5nlLMl8El9CVVbRFJWGcAN1gQin"
    "ps7x1pGjDirN4gsqGgB5Rr49+JH9UuszXEj+TKE6j+d7cE9PSkj5U8iFIF1tnXz3oWW/cejT"
    "EaBH5W169vZvP7h7w8uMz5wi76eRUoIQSEACNbpGqugwdiPF1blZ1jevJWipbZdrpi4qIq7u"
    "6l2/kQnnHIqoUqMEUYWGgoJAENQMUgWHizcknzw7wJGuAY5fu0RPxzpEXN2ltNsr+4g6SF+S"
    "LWWQsoL0FaqehiF05gopLk2rHN70DU1Rm4TrMF38FT2Wpt1e2acZQS9So9RwYS6JnlvL6eJZ"
    "mluKmHqIZMahOtfBZ10DrLBiJFyHV0c209EuMY0QWtCLaOFohJmlNLdnohx+8QBwgFfOr0aY"
    "ORqLnRx74XvqTYuE69D743OEm+4SDLTglj2scARtsejmJosTgcmlBQwlQL1mcfr5m4zf+Ykt"
    "Ld3Umxa/z0/yzlg/0aYEq+IxnGKG89kx3IqbU+aX54f+XnRobSuxbrCRtOfSGLR58/HXid/T"
    "fnesH6MhyYpYnGxJQ1NNpheSpIrzQ0ppSR1Mz0nClsWTawJ0Dq8iXXJBh4Tr8NqZzWgNKew6"
    "m8UKlKsCdIUFR1JaUgfV0njllr+BTXUNgTYrFCJkVvj8ypeE/Fo+/m0/nj1LvC6K70mQENBV"
    "lstVrl/Njqb2Fw4JAbQcNfVQRJlZ0xGzDU1FepLrs3d5JBInFNIplytYwQCqKih7Pn9OZpyl"
    "XLX5zr5C5X5MrV8FDV3Thhvbwt1hyyAc0dGECoAnffK5Cnm3TOJWfrTiedv+er/4f0wPsvpr"
    "c2u4VtuhqepOxRAmQLUsC57vn8gveidvvld4KOd/AYCuYU5d+dhHAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
Trash = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAY1J"
    "REFUOI2VkzFrFUEQx39zT3g8IZXBELtnIorYRFSwEARBIzEpTGFlb2k6SWGhBMRGv4etnV9B"
    "1MJGU4tIEC6Ru3e3M7tj8bj1qQc+B4bdhf/857ezrEgxoC8ePnris+eXzx5Lr1CKwV+5s7vn"
    "ZWV+cNj4wWHjZWW+s7vnfVrpCP7s+K/IRF3H/4n3Hz9nomOdY1kZ38uStlVCCDShpWmVEJTJ"
    "pKGeTKjqmrqqUdNMkg2ePn/Bg/vbvHv7AU2OxYgGo9VAG4ygRkqJlfGYT/v72aDo7uMpcmb1"
    "NKvnznNve5OtzTsMjy+wsX6LS1eucmJxkYtraywtL6Ma8gwygYYpVrSIqWIWSSkRoxFjt4+4"
    "e9ZmgmmhzTd+kd+02UAtzFcP2Iw2G9i8BIBqD4Gp9or7GMx6ZjA3gdA/g5TSdHXHAXcnpYQ7"
    "gOOeuvqshZlnHBRTr2uXL9AmSIWyfvMG5dEPRqMR45WzpGgMh0NEfn1Mmf3O12/f9S9fv1EU"
    "giCIgIjkdHdOLZ3kzetX2eEn6IoI1wsU3oEAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
Undefined = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAr9J"
    "REFUOI1lk11I01EYxn/n7+a/zW05mx+l87OcbiAWUUYXQRd9aEYIdRcYdBF0UzfRF31IdFGE"
    "3UR0ExTVRaMISpuFlBCkCRGW1jRDHaPmMpe1tvV3O10cI2MH3ovDeZ7nnPd5zyMEWWuH9Jxr"
    "IyevBYs7D4BkOM78jy4RPHkfeLQYLBYJ2GTtWT+FW7YtLW2iqgQ0ARkJPxMQnoFEpB+iTwJi"
    "9PRu4OdiAav0do5Y6g5VtK4D3QybG6BmOaypgcExuP4Uvs7B87eQ+HB5Uowc9gK/EADezoC7"
    "XcqDV6Ws2CdlZFbKdDq7Nh2Vcu8lKd3tUuLtDAggR0Azq2+f2r/dyrMhGA0lsVlNfInBzg7o"
    "D8L2tZBrgqQBt57Beg+MfFu1UoxfGMyh8cbx1i0bGj9+hvkMrHCZeNAP/hdQWQy9g7O0NFlw"
    "u2BqGiIxSKfBU24lGKs2NGx1zXoumE2w3Al2C1SXKPKbdxPUVjnZ4FFmHrv5z3E9F7DVNZsw"
    "FzqK88GYh9EwTExDOgO/DQlSMnxFETwH4NPYMA6rj+qSBRVzoUNDL8Kiw+txiM5BgQ1qSoB4"
    "kGtHqtAEnLmjyCtrfUxFYSAI8SSgF6GRSc4NT6qZFzrAYQUjDXZXHVvXqIuuBcBV6kM3K4z2"
    "9/NkknMmUtPdkdiy9jKXIgJYciFlQOWe92BygMnOxgYHmQykJRTYlZmkprs10ef1R79DsROs"
    "uqocDX4koONAPfc6Sql2K7Jl4bzYCdHvIPq8fg3oDoWmehIpKFoK9iUQi4OvHE7sgV1N8PIi"
    "pOYhT1eYRApCoakeoFsDEL0VbY8H4pMpA8pcaoyRGIS/qZbO31XPLnOp1h4PxCdFb0Vbdpi2"
    "zvrX+fK3NVQql4cmIF/lkXq32r8ajgVEjzMrTP/FWbTKNpeDlmV28ow0pAzi4Rm65EORFec/"
    "PdsbJ7pS1q4AAAAASUVORK5CYII=")

