#----------------------------------------------------------------------
# This file was generated by create.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

IconError = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAlpJ"
    "REFUOI2lkr1PU2EUh5+3t/fe3vbSllYaIaA0MNAADhoxYWAiiCF+gCQaF4mJDpowOfgPGDVx"
    "YzIsmrBCHFwcdDAMxEQ0IAJ+xBJDtQUhUuzXfe99HTQQIx+DZ/yd33nOR44Q/F/49krOnzp3"
    "fbZv4NZeHm23CRZ7ztyOdaTuhqJW9yW71njwaeH5Tj6xE+Bj99mjofbGV7Fa8OVWyawIst82"
    "j3U8fTy97wqfe/tNrSo4FmmqRkbqqaQ6SMR9CI2xqd5+c18Am8W+aKoupQUMrGs3sa4MozUk"
    "qasiVXJk356ATG+/bbU0jltRhSy6W7qjmcQP2ETj9vhk/wV7V4DneCOh403IQgH8xpburq0g"
    "M8scshT53OrIjoDMyYGk3XlkSHN/IBfm8dLvt8FLaUozrwl+mKVq8e3QI2En/wGIYmnM7/+O"
    "8+IZ7vISypXbbYIWmCaOZtBaX4MvqD/8C5DRa84bCV8nG8sozUREoqhCYate5dcRukFZutiG"
    "Rlt1uGvUCg/Anz/IHk5lQze6Eu7MO5TfBMfD+/oFonUIQM5Nox1sRpVdVNklLAUT6eWNi/n1"
    "iJb1xYaDV3sG1UYOpAIF3toqWks74dEJAoOXcd68RC2lQQ+AVOge2MJvJouVss84kbrvS+io"
    "tZ+gAA+oVBBWFcJvgO5HhCKoSgUlQCnIS0nSCtBsWXf8CqELW0eLW+CBciR6oB5vborK6D2E"
    "HYbJJ9gNjaiiAhMEAlEReEL9vkGutU2pmLmpHBfpKjwFTrmEk07j4eIl6lCaiSNdXOmhXI9s"
    "oWSfXs+JX1/m7hX1hFwuAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
IconMissing = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAkFJ"
    "REFUOI2Nk01PU1EQhp9pb7+4/cQioSxQiOxQEyImGncaKoGYNBI1sNGVv0H3LvwDunYpQUIg"
    "WMSEBQlGozGKGjB2IV+1ipSW3vZyue1xAbQQiGGSWZ05z3nfmTMiHIqepgEjcTJCn0dDByiU"
    "MJbW1NjmsP8FMLG/WPYBfM2Dxuj5VnXtQrsQ1hWO3VO7rMhsCNNz8OWnmiqO+G8Apf0Ab9OA"
    "kbp5mdjpRsXKupDZqJGdDogGoaUBZr7C85nKqiQDbYApAjTcKSRvX5HuOg/8SCvcmiACStUg"
    "dnlHyblW4e2CYvozk+aoP+4A4l1n6Ha7YH5ZVYu37ZpHEXBp4HULH1OKs6eE2AnpBuJa86DR"
    "3xSB+SVFwZSqp0oZskUobdVU6D6I6MLiH7jYDr8ThX6tPkhvOquIBISHtxQVBbmCkDUOj8ch"
    "4HbB42HYsiEalF7N4SBo2ZDJKjpajhjqEfHgGSwsK7D+BjXNAW/mIVR3vMt7PXK7BMu00N5/"
    "y+f1QMC7nF4n8SgCwHb5aJjLudPk1GKOcCSElVd5DeP7uDPUec/nj/Dq3eaxFPj0EJUKYP0a"
    "F4G4urryMhoNYZSOZ0H3wdpaDnndfN0BJMnOTuaLgkuDspL/pkuDfFEgOzsJJKtfWXUOpWjs"
    "iYV1RXFLsOyDr7o1qPMoNgyBzMSqfOhvA0znLsCW9NATPLEuk/q2sjNMwKvwaFSzZAlmbhHS"
    "I1Py6e4lwISD27gXParjaQIt2IfTpwNQLhnY+TGZu39onf8B+hDogI/O4koAAAAASUVORK5C"
    "YII=")

#----------------------------------------------------------------------
IconNew = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAnZJ"
    "REFUOI11k0tIlFEUx3/3zuubMb6sHCMTRVvUKrQSIRISURSEUVBxUeCmNoKEO9sGBbZs12Ii"
    "cyGpmKQkTom4SCQzCYwkSsfyNY6lQ+O857a4+cK6cDlw/o97zoW/EBw51Srvdh2O7HqceRkA"
    "RJbCxAIDYunxC2DkIFkcMLCrM01DXLhfebP2HDVXwHRpILQDr6bh2dBX+HzXJ1af1wJx7aCv"
    "jdyWQHmHUi+nlHriU8pzL62oWFRULKrGB2n19I3GyjuUIrclIMAmACuAymkebmz1um+UQ/e4"
    "4tOS4JhTkBrNB8BS5ce/kU/BacUdjyDL9Lp7H0WHxUpPlQSqKO6ubCoTdPbDl1VBKHL0YyIx"
    "jXX2Q1OZgOLuSqBKqsL2htZaC11jiq2wJidTMPnBf8ggHNN1KwxdY4rWWguqsL1BYhZ5HDZ4"
    "PQsZBszMzrP8fQEiS/vq6BrfFvzMzM6TYWiuwwaYRR4r0jCPuyDyO8jkQzdw/q+qYE+fmig9"
    "NI2lJshxlxukYUqcuUQTwObE0cX/dzYntMbIwUpsLeT1KQNpYCnpPcRLvWvUL5b0gs3UzUQI"
    "LC68PgWJnyErkR+D62srtzh5Te+djkIyBCq572QzQRrgyAYn4MhhfW0FdhYHpZhr6yMWAIsB"
    "9ixwFeqKPDCLBFsm2LPBmqm5sQBirq1PAqNsT/tI6tFIx0HaIbG1r09s6V46rjnJEGxP+4DR"
    "3SzY1OW+ZU5ddyPtoNLw6y3Egxq1Z8GJqyCkNtkc3xDvG84CicNhutQzhHmxEnuWFu2iSmmz"
    "eBBCH31ipnkvTOKfcS4dqUMa9Ui7jnM6HiYdHRBT1Ufi/AcWrPoYRXGRIwAAAABJRU5ErkJg"
    "gg==")

#----------------------------------------------------------------------
IconOk = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAA0pJ"
    "REFUOI1Vk11sU2UAhp/v/K3t6WnXrUf2w5RliE4uloAKDuZP4gZGxsARYzBi1MRww4UJwQsv"
    "IDF6wYVcEBM18cKRoDFLYLLJz7KZYJAZkDBiJBOYCmztetZ17WnXtT2nnzeI8Fy/efPcPELw"
    "MHI7W2lix2OB6M5oLGoCZDPZwj/L2RPMclL8wJkH9+K/A7kHgzLDe/o2du/u3MLTjz5FlFoA"
    "sixy+fYfHP/lLANDE6MYbBMDlO8fyL3o+Mwc+2Cf3ftED5nlLMl8El9CVVbRFJWGcAN1gQin"
    "ps7x1pGjDirN4gsqGgB5Rr49+JH9UuszXEj+TKE6j+d7cE9PSkj5U8iFIF1tnXz3oWW/cejT"
    "EaBH5W169vZvP7h7w8uMz5wi76eRUoIQSEACNbpGqugwdiPF1blZ1jevJWipbZdrpi4qIq7u"
    "6l2/kQnnHIqoUqMEUYWGgoJAENQMUgWHizcknzw7wJGuAY5fu0RPxzpEXN2ltNsr+4g6SF+S"
    "LWWQsoL0FaqehiF05gopLk2rHN70DU1Rm4TrMF38FT2Wpt1e2acZQS9So9RwYS6JnlvL6eJZ"
    "mluKmHqIZMahOtfBZ10DrLBiJFyHV0c209EuMY0QWtCLaOFohJmlNLdnohx+8QBwgFfOr0aY"
    "ORqLnRx74XvqTYuE69D743OEm+4SDLTglj2scARtsejmJosTgcmlBQwlQL1mcfr5m4zf+Ykt"
    "Ld3Umxa/z0/yzlg/0aYEq+IxnGKG89kx3IqbU+aX54f+XnRobSuxbrCRtOfSGLR58/HXid/T"
    "fnesH6MhyYpYnGxJQ1NNpheSpIrzQ0ppSR1Mz0nClsWTawJ0Dq8iXXJBh4Tr8NqZzWgNKew6"
    "m8UKlKsCdIUFR1JaUgfV0njllr+BTXUNgTYrFCJkVvj8ypeE/Fo+/m0/nj1LvC6K70mQENBV"
    "lstVrl/Njqb2Fw4JAbQcNfVQRJlZ0xGzDU1FepLrs3d5JBInFNIplytYwQCqKih7Pn9OZpyl"
    "XLX5zr5C5X5MrV8FDV3Thhvbwt1hyyAc0dGECoAnffK5Cnm3TOJWfrTiedv+er/4f0wPsvpr"
    "c2u4VtuhqepOxRAmQLUsC57vn8gveidvvld4KOd/AYCuYU5d+dhHAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
IconUnknown = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAr9J"
    "REFUOI1lk11I01EYxn/n7+a/zW05mx+l87OcbiAWUUYXQRd9aEYIdRcYdBF0UzfRF31IdFGE"
    "3UR0ExTVRaMISpuFlBCkCRGW1jRDHaPmMpe1tvV3O10cI2MH3ovDeZ7nnPd5zyMEWWuH9Jxr"
    "IyevBYs7D4BkOM78jy4RPHkfeLQYLBYJ2GTtWT+FW7YtLW2iqgQ0ARkJPxMQnoFEpB+iTwJi"
    "9PRu4OdiAav0do5Y6g5VtK4D3QybG6BmOaypgcExuP4Uvs7B87eQ+HB5Uowc9gK/EADezoC7"
    "XcqDV6Ws2CdlZFbKdDq7Nh2Vcu8lKd3tUuLtDAggR0Azq2+f2r/dyrMhGA0lsVlNfInBzg7o"
    "D8L2tZBrgqQBt57Beg+MfFu1UoxfGMyh8cbx1i0bGj9+hvkMrHCZeNAP/hdQWQy9g7O0NFlw"
    "u2BqGiIxSKfBU24lGKs2NGx1zXoumE2w3Al2C1SXKPKbdxPUVjnZ4FFmHrv5z3E9F7DVNZsw"
    "FzqK88GYh9EwTExDOgO/DQlSMnxFETwH4NPYMA6rj+qSBRVzoUNDL8Kiw+txiM5BgQ1qSoB4"
    "kGtHqtAEnLmjyCtrfUxFYSAI8SSgF6GRSc4NT6qZFzrAYQUjDXZXHVvXqIuuBcBV6kM3K4z2"
    "9/NkknMmUtPdkdiy9jKXIgJYciFlQOWe92BygMnOxgYHmQykJRTYlZmkprs10ef1R79DsROs"
    "uqocDX4koONAPfc6Sql2K7Jl4bzYCdHvIPq8fg3oDoWmehIpKFoK9iUQi4OvHE7sgV1N8PIi"
    "pOYhT1eYRApCoakeoFsDEL0VbY8H4pMpA8pcaoyRGIS/qZbO31XPLnOp1h4PxCdFb0Vbdpi2"
    "zvrX+fK3NVQql4cmIF/lkXq32r8ajgVEjzMrTP/FWbTKNpeDlmV28ow0pAzi4Rm65EORFec/"
    "PdsbJ7pS1q4AAAAASUVORK5CYII=")

#----------------------------------------------------------------------
IconWarning = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAm9J"
    "REFUOI2lkEtsTGEYhp//XOacGjNmiFZFNUxLRVq3hSAhERKX2KgNsbGSIAgbiZ0QibDSsKim"
    "EhPCgo2F2IiFxCXu4pKZYqYXPTOjVT1z5sycy2/BgigWvuRbfW++PM8rBP83yt+OH3o37cn0"
    "bjny1w/iD5vrWX9i9P5R+fneIfmma92JP+XERAr93euWTpq3+HFyYQxqFtbLMsWstaxj760n"
    "/1QYvLTRUGNT04k5kxjOlrCG4jQ0+6iann7RtdH4dwflsc31i9oX5IfynL89nzM36rHsJlLt"
    "yQVu1dv8WwU/KxSubJisJZrGEytaANhx4DN9fRkeXE0B8O5ODrccxJbsvm5PSCD84KzR2gHS"
    "Aenw/Okjhgb7wcmDk2fmbIXxgnV2QoLS5Q1zzLnL32uzNCL+UwAa1wwQ+AGFq18B8Koqr+4W"
    "+Ph2ZG7nNT78SlCtpdVpI9Ssm+DmwM3h1zw8rwqaCZqJ50VoXdSAOjl68ReF4nGzU59hrJRK"
    "P0gD9BjoMUrDLl9KASgCFIFXDYjGdea1JVZf2W5uBdAAlOSMc3p7irD4DEQEz/ku1nO4CELB"
    "d2Z+91UD7DGP1rYE2cxYL3BdHTkW2R9Z27lNKIPgC6QMiSghdiHLwfQK7r6Os3NVhogRx3dD"
    "CCSakMRM1Wgz3aqmt3ScVhsjhJb9A0iiGj7ScXj4/BNUygDoWkBFgAQqTsCsRpPU7LqTGoqm"
    "i6iBEouCFCihAqZBsqmZ1xcGAEg2NQNgeiFCDxE1BRRJCIjRU4ldNEzvllOiFVkLCP0Q35fU"
    "6TW+lGyQCkZUYNs6gRfi1wKklBQLlboBy933DbxL/oFnlTdXAAAAAElFTkSuQmCC")

